### DISCUSSION TITLE
Adding !important for util classes

### DISCUSSION THREAD

**Discussion by willmcvay** [reapit/elements#108] [Ideas]
Ok, so we all know `!important` rules should be used sparingly in CSS. There is however a use case I can see in Elements where it makes sense and I think would be generally accepted as valid i.e. utility classes. Wanted to float this with the team before thinking about implementing.

Consider this example:

```css
.el-card {
  margin: 1rem;
}

.el-mb-12 {
  margin: 3rem;
}
```
```html
<div class="el-card el-mb-12">Content</div>
```
I think it seems reasonable that the `.el-mb-12` modifier would only be applied by a developer if they wanted to override the default behaviour of `.el-card` - I can't see another use case. Because the rules are equally specific, the winning rule will depend on which selector is loaded last which seems like a pretty rubbish edge case.

Consider if I increase the specificity on `.el-card`

```css
.el-card {
  &.el-is-active {
    margin: 1rem;
  }
}

.el-mb-12 {
  margin: 3rem;
}

```
```html
<div class="el-card el-is-active el-mb-12">Content</div>
```

In this case because the `.el-is-active` class increases the specificity, the `.el-mb-12` modifier is rendered totally useless. If the developer intention was to add the modifier, their expectation surely would be that the modifier would win, right?

**Proposal: Add an `!important` to util classes**

Brutal, yes, but if the sole purpose of util classes is to override default behaviours, seems reasonable that we would guarantee that the override works in all use cases.

Our modified example:

```css
.el-card {
  &.el-is-active {
    margin: 1rem;
  }
}

.el-mb-12 {
  margin: 3rem !important;
}

```
```html
<div class="el-card el-is-active el-mb-12">Content</div>
```

In this case, our modified margin would always work. If the important flag is causing any inheritance issues, we can easily remove it without too much of an issue. My sense is, it's a far lesser evil that we use `!important` for utilities _only_ than having to worry about those utilities not working in some scenarios. 

Please comment, upvote or downvote as something we can look at in v5.
